//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Tank : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean MoveTank
        {
            get
            {
                return SteamVR_Actions.tank_MoveTank;
            }
        }
        
        public virtual SteamVR_Action_Boolean CalibrateTank
        {
            get
            {
                return SteamVR_Actions.tank_CalibrateTank;
            }
        }
        
        public virtual SteamVR_Action_Boolean FireCannon
        {
            get
            {
                return SteamVR_Actions.tank_FireCannon;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TankDirection
        {
            get
            {
                return SteamVR_Actions.tank_TankDirection;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.tank_Pose;
            }
        }
    }
}
